# Generated by Django 5.0.3 on 2024-03-16 19:50

from django.db import migrations

def load_initial_data(apps, schema_editor):
    model = apps.get_model('echoBudget', 'Category')
    model.objects.create(name = 'Food')
    model.objects.create(name = 'Housing')
    model.objects.create(name = 'Necessities')
    model.objects.create(name = 'Entertainment')
    model.objects.create(name = 'Transportation')
    model.objects.create(name = 'Others')

class Migration(migrations.Migration):

    dependencies = [
        ('echoBudget', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
    ]
