# Generated by Django 5.0.3 on 2024-03-22 17:22

from django.db import migrations
import datetime
from echoBudget.models import Category, Expense

def load_entry_data(apps, schema_editor):
    expense_model = apps.get_model('echoBudget', 'Expense')
    cat_food, cat_necessities, cat_housing = None, None, None
    # for obj in Expense.objects.all():
    #     if obj['name'] == 'Food':
    #         cat_food = obj
    #     elif obj['name'] == 'Necessities':
    #         cat_necessities = obj
    #     elif obj['name'] == 'Housing':
    #         cat_housing == obj
    # if not cat_food or not cat_necessities or not cat_housing:
    #     print("fail to find category")
    try:
        cat_food = Category.objects.get(name="Food")
        cat_housing = Category.objects.get(name='Housing')
        cat_necessities = Category.objects.get(name='Necessities')
    except:
        print("Fail to get categories")
    entry1 = Expense(date = datetime.datetime(2024, 2, 2), 
        amount = 12.99, item_name = 'revolution noodle', category = cat_food)
    entry1.save()
    entry2 = Expense(date = datetime.datetime(2024, 2, 21),
        amount = 150.00, item_name = 'clothes', category = cat_necessities)
    entry2.save()
    entry3 = Expense(date = datetime.datetime(2024, 3, 6),
        amount = 1100.00, item_name = 'rent', category = cat_housing)
    entry3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('echoBudget', '0002_auto_20240316_1550'),
    ]

    operations = [
        migrations.RunPython(load_entry_data),
    ]
