# Generated by Django 5.0.3 on 2024-03-22 20:14

from django.db import migrations
import datetime
from echoBudget.models import Category, Expense

def load_more_entry_data(apps, schema_editor):
    cat_food, cat_necessities, cat_housing = None, None, None
    try:
        cat_food = Category.objects.get(name="Food")
        cat_housing = Category.objects.get(name='Housing')
        cat_necessities = Category.objects.get(name='Necessities')
    except:
        print("Fail to get categories")
    entry1 = Expense(date = datetime.datetime(2024, 2, 3), 
        amount = 4.50, item_name = 'coffee', category = cat_food)
    entry1.save()
    entry2 = Expense(date = datetime.datetime(2024, 3, 9),
        amount = 98.55, item_name = 'hoodie', category = cat_necessities)
    entry2.save()
    entry3 = Expense(date = datetime.datetime(2024, 3, 14),
        amount = 3.00, item_name = 'apple', category = cat_food)
    entry3.save()

class Migration(migrations.Migration):

    dependencies = [
        ('echoBudget', '0003_auto_20240322_1322'),
    ]

    operations = [
        migrations.RunPython(load_more_entry_data),
    ]
